version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: agents/networking/Dockerfile
    env_file:
      - agents/networking/.env
    environment:
      REDIS_URL: redis://redis:6379/0
      CORS_ALLOW_ORIGINS: http://localhost:3000,http://frontend:3000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://backend:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - backend
