linkedin_profile_analyzer_task:
  description: >
    Extract comprehensive professional information from the LinkedIn profile data provided below.
    Focus on career progression, core skills, education, recent activity, and any noteworthy highlights.
    LinkedIn profile data:
    {linkedin_profile}
  expected_output: >
    A JSON object that matches networking.schemas.LinkedInProfileAnalyzerOutput with the following shape:
    {
      "profile_name": string | null,
      "headline": string | null,
      "current_title": string | null,
      "current_company": string | null,
      "location": string | null,
      "highlights": [string x 10]
    }
    Ensure "highlights" contains exactly ten concise bullet points covering experience, skills, education,
    recent activity, awards, and networking hooks. Respond with JSON only.
  agent: linkedin_profile_analyzer

summary_generator_task:
  description: >
    Create a concise 2-sentence professional summary using the LinkedIn profile data and the insights
    generated by the analyzer task.
    Always write about the person identified in the analyzer output (profile_name) and repeat their exact name
    in the first sentence. Do not introduce any other individual.
    Highlight the current role, company, years of experience, and standout expertise that would be most useful
    in a networking conversation.
    LinkedIn profile data:
    {linkedin_profile}
  expected_output: >
    A JSON object that matches networking.schemas.SummaryOutput with the following shape:
    {
      "summary": "Sentence one. Sentence two.",
      "key_highlights": [string x 3]
    }
    The summary must contain exactly two sentences and "key_highlights" must include exactly three
    supporting facts drawn from the analyzer insights. Respond with JSON only.
  agent: summary_generator
  context:
    - linkedin_profile_analyzer_task

icebreaker_generator_task:
  description: >
    Generate personalized conversation starters for networking using the LinkedIn profile data and the
    analyzer task output. Provide a mix of professional, educational, industry, and interest-based prompts
    tailored to what would resonate with the person profiled.
    LinkedIn profile data:
    {linkedin_profile}
  expected_output: >
    A JSON object that matches networking.schemas.IcebreakerOutput with the following shape:
    {
      "icebreakers": [
        {"category": "professional" | "educational" | "industry" | "interest" | "personal", "prompt": string}
      ]
    }
    Provide three to five icebreakers that cover a variety of categories. Prompts should be framed as natural,
    open-ended questions. Respond with JSON only.
  agent: icebreaker_generator
  context:
    - linkedin_profile_analyzer_task

profile_selector_task:
  description: >
    Review the LinkedIn candidate profiles listed below and select the single record that best matches the
    person we are searching for. Prioritize matches using the subtitle/headline, experience history, and
    location details. When the provided hints are sparse, strictly prioritize professionals based in leading
    US tech hubs (San Francisco Bay Area, Seattle, New York City, Austin) and in the broader United States
    before considering other regions.

    Candidate profiles:
    {candidate_profiles}

    Search criteria and hints:
    {search_criteria}
  expected_output: >
    A JSON object that matches networking.schemas.ProfileSelectionOutput with the following shape:
    {
      "selected_profile": { ... },
      "rationale": string | null
    }
    Ensure the selected profile object mirrors one of the candidates and includes all original keys. Only
    choose a non-US candidate if no acceptable US-based option exists. Respond with JSON only.
  agent: profile_selector
